# Generated by Django 4.0 on 2022-01-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='User',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
    ]
