# Generated by Django 4.0.1 on 2022-02-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='studentcertificate',
            field=models.ImageField(upload_to='studentcertifica'),
        ),
    ]
