# Generated by Django 4.0.1 on 2022-01-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('categoryImage', models.ImageField(upload_to='')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
    ]
