# Generated by Django 4.0.1 on 2022-02-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacherDescription',
            field=models.CharField(max_length=150),
        ),
    ]
