# Generated by Django 4.0.1 on 2022-02-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_teacher_teacherdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacherDescription',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
