# Generated by Django 4.0.1 on 2022-02-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_courses_description_alter_teacher_teacherdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='courseImage',
            field=models.ImageField(null=True, upload_to='courses'),
        ),
    ]
