# Generated by Django 4.0.1 on 2022-02-06 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_courses_courseimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='teacher',
        ),
        migrations.AddField(
            model_name='courses',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.teacher'),
        ),
    ]
