# Generated by Django 4.0 on 2022-01-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('birthday', models.DateTimeField()),
                ('gender', models.BooleanField()),
                ('tc', models.CharField(max_length=50)),
                ('studentcertificate', models.ImageField(upload_to='uploads')),
            ],
        ),
    ]
