# Generated by Django 4.0.1 on 2022-02-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCard', '0002_shopping_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping',
            name='teacher',
        ),
    ]
